#!/bin/bash
#
# bootstrap
#
# Get ready to develop

set -e

echo ""
echo "  Application Insigts Click Demo"
echo ""

#
# Prepare .env
#

echo ""
echo " Prepare .env"
echo ""

if test -f .env
then
  echo "  o .env found"
else
  echo "  + Creating .env"
  cp .env.sample .env
fi

source .env

#
# Set up instrumentation key
#

echo ""
echo " Set up instrumentation key"
echo ""

if [[ -z "${INSTRUMENTATION_KEY}" ]]; then
  echo " ERROR: INSTRUMENTATION_KEY is empty"
  echo " Usage: 'INSTRUMENTATION_KEY=xxxxx script/bootstrap' or set 'export INSTRUMENTATION_KEY=xxxxx; script/bootstrap'"
  exit 1
else
  find ./*.html -type f | xargs sed -i .bak "s/INSTRUMENTATION_KEY/${INSTRUMENTATION_KEY}/g"
fi

echo ""
echo "  Good work. We're ready."
echo ""

exit 0
